// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PadelPistas.Api.Data;

#nullable disable

namespace PadelPistas.Api.Migrations
{
    [DbContext(typeof(PadelPistasDbContext))]
    [Migration("20260719115206_AddTournaments")]
    partial class AddTournaments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("PadelPistas.Api.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Letra")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "Nivel", "Genero", "Letra")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PadelPistas.Api.Domain.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Club de ejemplo",
                            Slug = "lgancce"
                        });
                });

            modelBuilder.Entity("PadelPistas.Api.Domain.Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClubId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentMatch")
                        .HasColumnType("TEXT")
                        .HasColumnName("CurrentMatchJson");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Courts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClubId = 1,
                            CurrentMatch = "{\"teams\":[{\"players\":[{\"name\":\"Ana\",\"gender\":\"female\"},{\"name\":\"Luc\\u00EDa\",\"gender\":\"female\"}]},{\"players\":[{\"name\":\"Marta\",\"gender\":\"female\"},{\"name\":\"Sara\",\"gender\":\"female\"}]}],\"score\":{\"currentPoint\":[30,40],\"games\":[[6,4],[3,5]],\"sets\":[1,0]}}",
                            Nombre = "Pista Central",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            ClubId = 1,
                            CurrentMatch = "{\"teams\":[{\"players\":[{\"name\":\"Carlos\",\"gender\":\"male\"},{\"name\":\"Javier\",\"gender\":\"male\"}]},{\"players\":[{\"name\":\"Diego\",\"gender\":\"male\"},{\"name\":\"Pablo\",\"gender\":\"male\"}]}],\"score\":{\"currentPoint\":[\"AD\",40],\"games\":[[5,5]],\"sets\":[0,0]}}",
                            Nombre = "Pista 2",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            ClubId = 1,
                            Nombre = "Pista 3",
                            Orden = 3
                        });
                });

            modelBuilder.Entity("PadelPistas.Api.Domain.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Telefonos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("PadelPistas.Api.Domain.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Disponibilidad")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DisponibilidadJson");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Pagada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Player1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Player2Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.HasIndex("CategoryId", "Player1Id", "Player2Id")
                        .IsUnique();

                    b.ToTable("Registrations", t =>
                        {
                            t.HasCheckConstraint("CK_Registrations_ParejaOrdenada", "\"Player1Id\" < \"Player2Id\"");
                        });
                });

            modelBuilder.Entity("PadelPistas.Api.Domain.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClubId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InscripcionApertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InscripcionCierre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PistasDisponibles")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("PadelPistas.Api.Domain.TournamentMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GanadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Registration1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Registration2Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resultado")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Registration1Id");

                    b.HasIndex("Registration2Id");

                    b.ToTable("TournamentMatches");
                });

            modelBuilder.Entity("PadelPistas.Api.Domain.Category", b =>
                {
                    b.HasOne("PadelPistas.Api.Domain.Tournament", "Tournament")
                        .WithMany("Categories")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("PadelPistas.Api.Domain.Court", b =>
                {
                    b.HasOne("PadelPistas.Api.Domain.Club", "Club")
                        .WithMany("Courts")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("PadelPistas.Api.Domain.Registration", b =>
                {
                    b.HasOne("PadelPistas.Api.Domain.Category", "Category")
                        .WithMany("Registrations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PadelPistas.Api.Domain.Player", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PadelPistas.Api.Domain.Player", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Player1");

                    b.Navigation("Player2");
                });

            modelBuilder.Entity("PadelPistas.Api.Domain.Tournament", b =>
                {
                    b.HasOne("PadelPistas.Api.Domain.Club", "Club")
                        .WithMany("Tournaments")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("PadelPistas.Api.Domain.TournamentMatch", b =>
                {
                    b.HasOne("PadelPistas.Api.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PadelPistas.Api.Domain.Registration", "Registration1")
                        .WithMany()
                        .HasForeignKey("Registration1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PadelPistas.Api.Domain.Registration", "Registration2")
                        .WithMany()
                        .HasForeignKey("Registration2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Registration1");

                    b.Navigation("Registration2");
                });

            modelBuilder.Entity("PadelPistas.Api.Domain.Category", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("PadelPistas.Api.Domain.Club", b =>
                {
                    b.Navigation("Courts");

                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("PadelPistas.Api.Domain.Tournament", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
