// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PadelPistas.Api.Data;

#nullable disable

namespace PadelPistas.Api.Migrations
{
    [DbContext(typeof(PadelPistasDbContext))]
    partial class PadelPistasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("PadelPistas.Api.Domain.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Club de ejemplo",
                            Slug = "lgancce"
                        });
                });

            modelBuilder.Entity("PadelPistas.Api.Domain.Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClubId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentMatch")
                        .HasColumnType("TEXT")
                        .HasColumnName("CurrentMatchJson");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Courts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClubId = 1,
                            CurrentMatch = "{\"teams\":[{\"players\":[{\"name\":\"Ana\",\"gender\":\"female\"},{\"name\":\"Luc\\u00EDa\",\"gender\":\"female\"}]},{\"players\":[{\"name\":\"Marta\",\"gender\":\"female\"},{\"name\":\"Sara\",\"gender\":\"female\"}]}],\"score\":{\"currentPoint\":[30,40],\"games\":[[6,4],[3,5]],\"sets\":[1,0]}}",
                            Nombre = "Pista Central",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            ClubId = 1,
                            CurrentMatch = "{\"teams\":[{\"players\":[{\"name\":\"Carlos\",\"gender\":\"male\"},{\"name\":\"Javier\",\"gender\":\"male\"}]},{\"players\":[{\"name\":\"Diego\",\"gender\":\"male\"},{\"name\":\"Pablo\",\"gender\":\"male\"}]}],\"score\":{\"currentPoint\":[\"AD\",40],\"games\":[[5,5]],\"sets\":[0,0]}}",
                            Nombre = "Pista 2",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            ClubId = 1,
                            Nombre = "Pista 3",
                            Orden = 3
                        });
                });

            modelBuilder.Entity("PadelPistas.Api.Domain.Court", b =>
                {
                    b.HasOne("PadelPistas.Api.Domain.Club", "Club")
                        .WithMany("Courts")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("PadelPistas.Api.Domain.Club", b =>
                {
                    b.Navigation("Courts");
                });
#pragma warning restore 612, 618
        }
    }
}
